defaults: &defaults
  line:
    channel_secret: ''
    channel_token: ''
  google:
    google_api_key: ''
  facebook:
    app_id: ''
    app_secret: ''
    app_access_token: ''
    access_token: ''

development:
  <<: *defaults