defaults: &defaults
  adapter:  postgresql
  encoding: utf8
  database: 'foodcraw_development'
  pool:     5
  host:     '127.0.0.1'
  username: 'john'
  password: ''

development:
  <<: *defaults

test:
  <<: *defaults
  database: 'foodcraw_test'

production:
  <<: *defaults
  database: 'foodcraw_production'
  url:      <%= ENV["DATABASE_URL"] %>
