defaults: &defaults
  adapter:  postgresql
  encoding: utf8
  database: 'foodsearch_development'
  pool:     5
  host:     localhost
  username: 'john'
  password: ''

development:
  <<: *defaults

test:
  <<: *defaults
  database: 'foodsearch_test'

production:
  <<: *defaults
  database: 'foodsearch_production'
