defaults: &defaults
  adapter: postgresql
  encoding: 'unicode'
  database: 'foodsearch_development'
  pool: 5
  host: '127.0.0.1'
  username: 'john'
  password: ''

development:
  <<: *defaults

test:
  <<: *defaults
  database: 'foodsearch_test'